### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by lucheng07082221** [johncava/GCN-pytorch#1]
hi：can you share your datasets？thank you！

**Comment by johncava** [comment]
Dataset is the Zachary Karate Club dataset. You can find the info in the .gml file from http://networkdata.ics.uci.edu/data/karate/

**Comment by lucheng07082221** [comment]
@johncava 
thanks.
another problem is x , y = read_data('karate.data', 'label.data') what the karate.data and label.data meaning?

**Comment by johncava** [comment]
karate data is the edge and node data. In this case the labels were for determining which "class" or "clique" each node belonged to.

**Comment by lucheng07082221** [comment]
@johncava How  can I know  the labels were for determining which "class" ? The datasets does not contain labels
